# Generated by Django 4.0.2 on 2022-02-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('k', 'King'), ('q', 'Queen'), ('r', 'Rook'), ('b', 'Bishop'), ('n', 'Knight'), ('p', 'Pawn')], max_length=1)),
                ('color', models.BooleanField(choices=[(True, 'White'), (False, 'Black')])),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
            ],
        ),
    ]
